export const GET_ERRORS = "GET_ERRORS";

export const GET_BUILDINGS_TYPE = "GET_BUILDINGS_TYPE";
export const GET_BUILDINGS_EMPTY = "GET_BUILDINGS_EMPTY";
export const UPDATE_BUILDING = "UPDATE_BUILDING";