export const GET_ERRORS = "GET_ERRORS";
export const GET_PROJECTS = "GET_PROJECTS";
export const GET_PROJECT = "GET_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";

export const GET_BUILDINGS_TYPE = "GET_BUILDINGS_TYPE";
export const GET_BUILDINGS_EMPTY = "GET_BUILDINGS_EMPTY";